name: C++ CI

# Pushイベントでmainブランチに変更があった場合
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # リポジトリのコードをGitHub Actionsにチェックアウト
    - name: Checkout code
      uses: actions/checkout@v2
      
    # VisualStudio2022を使用してビルド構成を作成
    - name: Configure CMake
      run: |
        # buildディレクトリへ移動
        cd build
        # ビルド構成を作成
        cmake .. -G "Visual Studio 17 2022"

    # プロジェクトをRelease設定でビルド
    - name: Build project
      run: |
        cd project_root/build
        cmake --build . --config Debug

    # CMakeのテストランナーを使ってテストを実行
    - name: Run testscd
      run: |
        cd project_root/build
        ctest
