name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get GoogleTest
      run: |
        cd project_root
        git submodule add https://github.com/google/googletest.git extern/googletest
        git submodule update --init --recursive
        
    - name: Configure CMake
      run: |
        cd project_root/build
        cmake .. -G "Visual Studio 17 2022"

    # プロジェクトをRelease設定でビルド
    - name: Build project
      run: |
        cd project_root/build
        cmake --build . --config Debug

    # CMakeのテストランナーを使ってテストを実行
    - name: Run testscd
      run: |
        cd project_root/build
        ctest
